const { Client } = require('pg');

const connStr = "postgresql://postgres.qhnqgsdprnedynbradxx:11223344556677889900mm@aws-1-eu-west-1.pooler.supabase.com:5432/postgres";

const client = new Client({
  connectionString: connStr,
});

async function run() {
  try {
    await client.connect();
    console.log("Connected to Supabase.");

    const sql = `
      -- 1. Create the working_hours table
      CREATE TABLE IF NOT EXISTS working_hours (
        id bigint generated by default as identity primary key,
        start_date date not null,
        end_date date,
        check_in_time time not null,
        check_out_time time not null,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );

      -- 2. Insert your current default shift starting from March 26th, 2024
      INSERT INTO working_hours (start_date, end_date, check_in_time, check_out_time)
      VALUES ('2024-03-26', NULL, '08:00:00', '17:30:00');

      -- 3. Policies
      ALTER TABLE working_hours ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS "Allow read access to anyone" ON working_hours;
      DROP POLICY IF EXISTS "Allow update access to admins" ON working_hours;
      CREATE POLICY "Allow read access to anyone" ON working_hours FOR SELECT USING (true);
      CREATE POLICY "Allow update access to admins" ON working_hours FOR ALL USING (true);
    `;

    await client.query(sql);
    console.log("Working hours schema installed successfully.");

  } catch (err) {
    console.error("Error running schema", err);
  } finally {
    await client.end();
  }
}

run();
