-- 1. Create the working_hours table
CREATE TABLE IF NOT EXISTS working_hours (
  id bigint generated by default as identity primary key,
  start_date date not null,
  end_date date,
  check_in_time time not null,
  check_out_time time not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Insert your current default shift starting from January 1st, 2024 (Null end_date means it runs forever until a new rule is made)
INSERT INTO working_hours (start_date, end_date, check_in_time, check_out_time)
VALUES ('2024-01-01', NULL, '08:00:00', '17:30:00');

-- 3. Required Policies for anonymous/authenticated access
ALTER TABLE working_hours ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read access to anyone" ON working_hours FOR SELECT USING (true);
CREATE POLICY "Allow update access to admins" ON working_hours FOR ALL USING (true);
