CREATE TABLE IF NOT EXISTS __ef_migrations_history (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE TABLE "CheckIns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpId" text NOT NULL,
    "State" text NOT NULL,
    "CheckInTime" timestamp with time zone,
    "CheckOutTime" timestamp with time zone,
    CONSTRAINT "PK_CheckIns" PRIMARY KEY ("Id")
);

CREATE TABLE "Employees" (
    "Id" text NOT NULL,
    "Name" text NOT NULL,
    "Department" text NOT NULL,
    "Position" text NOT NULL,
    "Joined" timestamp with time zone NOT NULL,
    "TotalHolidays" integer NOT NULL,
    "UsedHolidays" integer NOT NULL,
    "Password" text NOT NULL,
    "Role" text NOT NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id")
);

CREATE TABLE "HolidayRequests" (
    "RequestId" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpId" text NOT NULL,
    "EmpName" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "Days" integer NOT NULL,
    "Reason" text,
    "ManagerId" text NOT NULL,
    "ManagerStatus" text NOT NULL,
    "GMId" text NOT NULL,
    "GMStatus" text NOT NULL,
    "Status" text NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HolidayRequests" PRIMARY KEY ("RequestId")
);

CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260324221111_InitialSupabase', '9.0.2');

ALTER TABLE "Roles" DROP CONSTRAINT "PK_Roles";

ALTER TABLE "Employees" DROP CONSTRAINT "PK_Employees";

ALTER TABLE "HolidayRequests" DROP CONSTRAINT "PK_HolidayRequests";

ALTER TABLE "CheckIns" DROP CONSTRAINT "PK_CheckIns";

ALTER TABLE "Roles" RENAME TO roles;

ALTER TABLE "Employees" RENAME TO employees;

ALTER TABLE "HolidayRequests" RENAME TO holiday_requests;

ALTER TABLE "CheckIns" RENAME TO check_ins;

ALTER TABLE roles RENAME COLUMN "Name" TO name;

ALTER TABLE roles RENAME COLUMN "Id" TO id;

ALTER TABLE employees RENAME COLUMN "Role" TO role;

ALTER TABLE employees RENAME COLUMN "Position" TO position;

ALTER TABLE employees RENAME COLUMN "Password" TO password;

ALTER TABLE employees RENAME COLUMN "Name" TO name;

ALTER TABLE employees RENAME COLUMN "Joined" TO joined;

ALTER TABLE employees RENAME COLUMN "Department" TO department;

ALTER TABLE employees RENAME COLUMN "Id" TO id;

ALTER TABLE employees RENAME COLUMN "UsedHolidays" TO used_holidays;

ALTER TABLE employees RENAME COLUMN "TotalHolidays" TO total_holidays;

ALTER TABLE holiday_requests RENAME COLUMN "Status" TO status;

ALTER TABLE holiday_requests RENAME COLUMN "Reason" TO reason;

ALTER TABLE holiday_requests RENAME COLUMN "Days" TO days;

ALTER TABLE holiday_requests RENAME COLUMN "SubmittedAt" TO submitted_at;

ALTER TABLE holiday_requests RENAME COLUMN "StartDate" TO start_date;

ALTER TABLE holiday_requests RENAME COLUMN "ManagerStatus" TO manager_status;

ALTER TABLE holiday_requests RENAME COLUMN "ManagerId" TO manager_id;

ALTER TABLE holiday_requests RENAME COLUMN "GMStatus" TO gm_status;

ALTER TABLE holiday_requests RENAME COLUMN "GMId" TO gm_id;

ALTER TABLE holiday_requests RENAME COLUMN "EndDate" TO end_date;

ALTER TABLE holiday_requests RENAME COLUMN "EmpName" TO emp_name;

ALTER TABLE holiday_requests RENAME COLUMN "EmpId" TO emp_id;

ALTER TABLE holiday_requests RENAME COLUMN "RequestId" TO request_id;

ALTER TABLE check_ins RENAME COLUMN "State" TO state;

ALTER TABLE check_ins RENAME COLUMN "Id" TO id;

ALTER TABLE check_ins RENAME COLUMN "EmpId" TO emp_id;

ALTER TABLE check_ins RENAME COLUMN "CheckOutTime" TO check_out_time;

ALTER TABLE check_ins RENAME COLUMN "CheckInTime" TO check_in_time;

ALTER TABLE roles ADD CONSTRAINT pk_roles PRIMARY KEY (id);

ALTER TABLE employees ADD CONSTRAINT pk_employees PRIMARY KEY (id);

ALTER TABLE holiday_requests ADD CONSTRAINT pk_holiday_requests PRIMARY KEY (request_id);

ALTER TABLE check_ins ADD CONSTRAINT pk_check_ins PRIMARY KEY (id);

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260331155555_FixSnakeCaseConflicts', '9.0.2');

COMMIT;

