// <auto-generated />
using System;
using KtcBackend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KtcBackend.Migrations
{
    [DbContext(typeof(KtcContext))]
    [Migration("20260331155555_FixSnakeCaseConflicts")]
    partial class FixSnakeCaseConflicts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KtcBackend.CheckInStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_time");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_check_ins");

                    b.ToTable("check_ins", (string)null);
                });

            modelBuilder.Entity("KtcBackend.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<DateTime>("Joined")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("TotalHolidays")
                        .HasColumnType("integer")
                        .HasColumnName("total_holidays");

                    b.Property<int>("UsedHolidays")
                        .HasColumnType("integer")
                        .HasColumnName("used_holidays");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("KtcBackend.HolidayRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_id");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_name");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("GMId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gm_id");

                    b.Property<string>("GMStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gm_status");

                    b.Property<string>("ManagerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manager_id");

                    b.Property<string>("ManagerStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manager_status");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("RequestId")
                        .HasName("pk_holiday_requests");

                    b.ToTable("holiday_requests", (string)null);
                });

            modelBuilder.Entity("KtcBackend.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
